### ISSUE TITLE
Compatibility with TypeScript 2.9

### ISSUE THREAD

**Issue by hach-que** [NaridaL/subtractiontype.ts#1]
TypeScript 2.9 modified the definition of `keyof O` such that it is now `string|number|symbol` instead of just `string`. This causes compilation errors in subtractiontype.ts because number isn't compatible with `keyof O`.

I believe the fix for newer TypeScript versions is:

```

/**
 * for literal unions
 * @example Sub<'Y' | 'X', 'X'> // === 'Y'
 */
export type Sub<
    O extends string|number|symbol,
    D extends string|number|symbol
    > = {[K in O]: (Record<D, never> & Record<string|number|symbol, K>)[K]}[O]

type A = Sub<'x' | 'y', 'x'>

/**
 * Remove the keys represented by the string union type D from the object type O.
 *
 * @example Dissoc<{a: number, b: string}, 'a'> // === {b: string}
 * @example Dissoc<{a: number, b: string}, keyof {a: number}> // === {b: string}
 */
export type Dissoc<O, D extends string|number|symbol> = Pick<O, Sub<keyof O, D>>



export as namespace nla
```

**Comment by hach-que** [comment]
The current workaround is to set `"keyofStringsOnly": true` in `compilerOptions` inside `tsconfig.json`.

**Comment by NaridaL** [comment]
Hi! Since 2.8 `Exclude` is built into TypeScript, you should use that. See https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-8.html#predefined-conditional-types for more details. I will update the readme to avoid further confusion.

**Comment by hach-que** [comment]
Thanks for the response. I was actually using `Dissoc`, which doesn't have an equivalent built-in in TypeScript >=2.8 but can be obtained with this declaration (basically same as the one provided in this library):

```
type Dissoc<O, D extends string> = Pick<O, Exclude<keyof O, D>>;
```

It might be a good idea to add that to the README as well for anyone that was using this library for the Dissoc type.
